# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Coalition for Refugees from Burma
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coalition for Refugees from Burma (CRB) is a 501(c)(3) non-profit mutual assistance association focused on providing culturally and linguistically appropriate social support services to improve the living conditions and quality of life of refugees resettled in Washington State.
tagline: We help refugees.
jQuery: <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
sticky-nav: <script src="/js/sticky_nav.js"></script>
kon: <script type="text/javascript" src="/js/kon.js"></script>
mobile-nav: <script type="text/javascript" src="/js/menu.js"></script>


baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# sass settings
sass:
  sass_dir: styles
  style: :compressed

# defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# include pages folder
include: ["_pages"]

# make title the default link URL
permalink: /:title/
